// front/src/components/post/Comment.jsx
import {
  Delete,
  Edit,
} from '@mui/icons-material'
import {
  Box,
  Button,
  Typography,
} from '@mui/material'
import { T, useI18n } from '@src/i18n'

export default function Comment({
  comment,
  onEditComment = () => {},
  onDeleteComment = () => {},
}) {
  const { locale } = useI18n()
  const text = comment.text ?? ''
  const authorName = comment.author?.fullName ?? ''
  const commentDate = comment.date ? new Date(comment.date) : null
  const dateString = commentDate?.toLocaleDateString(locale, { day: '2-digit', month: '2-digit', year: 'numeric' })
  const timeString = commentDate?.toLocaleTimeString(locale, { hour: '2-digit', minute: '2-digit' })
  const dateAsString = dateString && timeString ? `${dateString} @ ${timeString}` : ''
  return (
    <Box sx={{ display: 'flex', gap: 2, p: 2, border: '1px solid #ddd' }}>
      <Box sx={{ flexGrow: 1 }}>
        <Typography variant="subtitle2">
          By
          {' '}
          <span>{authorName}</span>
          {' '}
          on
          {' '}
          <span>{dateAsString}</span>
        </Typography>
        <Typography>{text}</Typography>
      </Box>
      <Box sx={{ display: 'flex', flexDirection: 'column', gap: 1 }}>
        <Button
          startIcon={<Edit />}
          color="secondary"
          onClick={onEditComment}
          size="small"
          variant="outlined"
        >
          <T>Edit</T>
        </Button>
        <Button
          startIcon={<Delete />}
          color="error"
          onClick={onDeleteComment}
          size="small"
          variant="outlined"
        >
          <T>Delete</T>
        </Button>
      </Box>
    </Box>
  )
}

// front/src/components/post/Comment.vue
<script>
export default {
  name: 'Comment',
  props: {
    comment: {
      type: Object,
      default: () => ({
        text: '',
        author: null,
        date: null,
      }),
    },
  },
  emits: [
    'editComment',
    'deleteComment',
  ],
  computed: {
    text () {
      return this.comment.text || ''
    },
    authorName () {
      return this.comment.author ? this.comment.author.fullName || '' : ''
    },
    commentDate () {
      return this.comment.date ? new Date(this.comment.date) : null
    },
    dateAsString () {
      if (this.commentDate) {
        const lang = this.$language.current
        const date = this.commentDate
        const dateString = date.toLocaleDateString(lang, { day: '2-digit', month: '2-digit', year: 'numeric' })
        const timeString = date.toLocaleTimeString(lang, { hour: '2-digit', minute: '2-digit' })
        return date ? `${dateString} @ ${timeString}` : ''
      } else {
        return ''
      }
    },
  },
  methods: {
    onEditComment () {
      this.$emit('editComment', this.comment)
    },
    onDeleteComment () {
      this.$emit('deleteComment', this.comment)
    },
  },
}
</script>
<template>
  <div class="comment card">
    <div class="comment-content">
      <div class="comment-header">
        {{ $gettext('By') }}
        <span class="comment-author">{{ authorName }}</span>
        {{ $gettext('On') }}
        <span class="comment-date">{{ dateAsString }}</span>
      </div>
      <div class="comment-text">
        {{ text }}
      </div>
    </div>
    <div class="comment-actions">
      <v-btn
        prepend-icon="fas fa-pen"
        color="secondary"
        class="edit"
        @click="onEditComment"
      >
        {{ $gettext('Edit') }}
      </v-btn>
      <v-btn
        prepend-icon="fas fa-trash"
        color="secondary"
        class="delete"
        variant="tonal"
        @click="onDeleteComment"
      >
        {{ $gettext('Delete') }}
      </v-btn>
    </div>
  </div>
</template>
<style lang="scss" scoped>
.comment {
  flex-direction: row;
}
.comment-content {
  display: flex;
  flex-direction: column;
  flex-grow: 1;
  flex-shrink: 1;
}
.comment-actions {
  display: flex;
  flex-direction: column;
  gap: 1ch;
  flex-grow: 0;
  flex-shrink: 0;
}
.comment-header {
  font-weight: 300;
  font-size: 1.1rem;
  margin-bottom: 1rem;
}
.comment-author {
  font-weight: 700;
  color: $secondary-dark;
}
</style>
