// front/src/components/PostCard.jsx
import { T, useI18n } from '@src/utils/i18n'
import { useState } from 'react'
import { Chip, Stack, Button } from '@mui/material'
import CancelIcon from '@mui/icons-material/Cancel'
import DeleteIcon from '@mui/icons-material/Delete'
import EnterIcon from '@mui/icons-material/ArrowRight'
import InformationPopup from '@comp/utils/InformationPopup'
import './PostCard.scoped.scss'

export default function PostCard({
  post,
  onEnterPost = () => {},
  onDeletePost = () => {},
}) {
  const { t } = useI18n()
  const categoryNames = post.categories?.map(cat => cat.name) ?? []
  const authorName = post.author?.fullName ?? ''
  const publicationDate = new Date(post.pubdate)
  const $language = { current: 'fr' }
  const localeDate = publicationDate.toLocaleDateString($language.current)
  const localeTime = publicationDate.toLocaleTimeString($language.current)
  const [deletePostDialogShown, setDeletePostDialogShown] = useState(false)
  const deletePostDialogButtons = [
    {
      type: 'cancel',
      label: t('Cancel'),
      icon: (<CancelIcon />),
    },
    {
      type: 'submit',
      label: t('Confirm'),
      icon: (<DeleteIcon />),
    },
  ]
  function showDeletePostDialog() {
    setDeletePostDialogShown(true)
  }
  function hideDeletePostDialog() {
    setDeletePostDialogShown(false)
  }
  function deletePost() {
    hideDeletePostDialog()
    onDeletePost(post)
  }
  function enterPost() {
    onEnterPost(post)
  }
  return (
    <div className="post">
      <div className="header">
        <div className="title">{ post.title }</div>
        { categoryNames.length && (
          <Stack className="categories" direction="row" spacing={1}>
            {categoryNames.forEach(category => { (
              <Chip key="category" label={category} />
            ) })}
          </Stack>
        )}
      </div>
      <div className="author-date">
        <span>
          <T>Published by</T>
        </span>
        <span className="author">{ authorName }</span>
        <span className="publication-date">
          <T one="on {{ localeDate }} at {{ localTime }}" localeDate={localeDate} localeTime={localeTime} />
        </span>
      </div>
      <div className="actions">
        <Button
          variant="text"
          size="small"
          color="secondary"
          startIcon={(<DeleteIcon />)}
          onClick={showDeletePostDialog}
        />
        <Button
          variant="text"
          size="small"
          color="secondary"
          startIcon={(<EnterIcon />)}
          onClick={enterPost}
        />
      </div>
      <InformationPopup
        open={deletePostDialogShown}
        title={t('Delete a blog post')}
        buttons={deletePostDialogButtons}
        onCancel={hideDeletePostDialog}
        onSubmit={deletePost}
      >
        <div>
          <T
            one="You are about to delete the blog post « {{ post }} ». Do you really want to take that action?"
            post={post.title}
          />
        </div>
      </InformationPopup>
    </div>
  )
}

// front/src/components/PostCard.vue
<script>
import InformationPopup from '@comp/utils/InformationPopup.vue'

export default {
  name: 'PostCard',
  components: {
    InformationPopup,
  },
  props: {
    item: {
      type: Object,
      required: true,
    },
  },
  emits: [
    'deletePost',
    'enterPost',
  ],
  data () {
    return {
      post: {
        title: '',
        categories: [],
        author: null,
        pubdate: null,
      },
      showDeletePostDialog: false,
    }
  },
  computed: {
    categoryNames () {
      return this.post.categories ? this.post.categories.map(cat => cat.name) : []
    },
    authorName () {
      return this.post.author ? this.post.author.fullName : ''
    },
    deletePostDialogButtons () {
      return [
        {
          class: 'cancel-btn',
          label: this.$gettext('Cancel'),
          icon: 'fas fa-times',
          event: 'cancelDeletePostDialog',
        },
        {
          class: 'delete-btn',
          label: this.$gettext('Confirm'),
          icon: 'fas fa-trash',
          color: 'white',
          event: 'deletePost',
        },
      ]
    },
    publicationDate () {
      return new Date(this.post.pubdate)
    },
    localeDate () {
      return this.publicationDate.toLocaleDateString(this.$language.current)
    },
    localeTime () {
      return this.publicationDate.toLocaleTimeString(this.$language.current)
    },
  },
  mounted () {
    this.setData()
  },
  methods: {
    setData () {
      this.post = this.item
    },
    deletePost () {
      this.showDeletePostDialog = false
      this.$emit('deletePost', this.post)
    },
    toggleDeletePostDialog () {
      this.showDeletePostDialog = !this.showDeletePostDialog
    },
    enterPost (post) {
      this.$emit('enterPost', post)
    },
  },
}
</script>
<template>
  <div class="post card card-hover">
    <div class="post-header">
      <div class="post-title">
        {{ post.title }}
      </div>
      <div
        v-if="categoryNames.length"
        class="post-categories"
      >
        <v-chip
          v-for="category in categoryNames"
          :key="category"
          label
        >
          {{ category }}
        </v-chip>
      </div>
    </div>
    <div class="post-author-date">
      <span>{{ `${$gettext('Published by')} ` }}</span>
      <span class="author">{{ authorName }}</span>
      <span class="publication-date">
        {{ ` ${$gettext('on')} ${localeDate} ${$gettext('at')} ${localeTime}` }}
      </span>
    </div>
    <div class="post-actions">
      <v-btn
        variant="text"
        size="small"
        icon="fas fa-trash"
        color="secondary"
        @click="toggleDeletePostDialog"
      />
      <v-btn
        variant="text"
        size="small"
        icon="fas fa-arrow-right"
        color="secondary"
        @click="enterPost(post)"
      />
    </div>
    <InformationPopup
      v-model="showDeletePostDialog"
      :title="$gettext('Delete a blog post')"
      :buttons="deletePostDialogButtons"
      @cancel-delete-post-dialog="toggleDeletePostDialog"
      @delete-post="deletePost"
    >
      <div>
        {{ `${$gettext('You are about to delete the blog post')} « ${post.title} ».
          ${$gettext('Do you really want to take that action?')}` }}
      </div>
    </InformationPopup>
  </div>
</template>
<style lang="scss" scoped>
.post.card {
  display: flex;
  flex-direction: column;
  gap: 1ch;
}
.post-title {
  font-size: 1.4rem;
}
.post-author-date {
  font-weight: 300;
}
.post-categories {
  display: flex;
  flex-direction: row;
  gap: 1ch;
}
.post-actions button + button {
  margin-left: '20px';
}
.author {
  font-weight: 700;
}
</style>
