// front/src/pages/MapPage.vue
<script>
import { LngLatBounds } from 'mapbox-gl'
import { MapboxMap, MapboxNavigationControl, MapboxMarker } from '@studiometa/vue-mapbox-gl'
import { mapboxPublicKey } from '@src/config'
import pkPoints from '@static/markers.json'
import line from '@static/line.json'
import { useIndexStore } from '@src/store'
import colorShades from '@scss/sds-design-system/color-shades'

export default {
  name: 'MapPage',
  components: {
    MapboxMap,
    MapboxNavigationControl,
    MapboxMarker,
  },
  data () {
    return {
      map: null,
      showLeftPanel: false,
      showLeftPanelContent: false,
      checkPk: true,
      checkLine: true,
      points: pkPoints.features,
      mapboxPublicKey: null,
      line: {},
    }
  },
  watch: {
    showLeftPanel (val) {
      if (val) {
        // Leave time for animation to end (.fade-enter-active css rule)
        setTimeout(() => {
          this.showLeftPanelContent = true
        }, 500)
      } else {
        this.showLeftPanelContent = false
      }
    },
  },
  created () {
    this.mapboxPublicKey = mapboxPublicKey
    this.line = line
  },
  mounted () {
    const store = useIndexStore()
    store.changeRoute(this.$options.name)
  },
  methods: {
    toggleShowLeftPanel () {
      this.showLeftPanel = !this.showLeftPanel
    },
    onCheckLine (newValue) {
      const opacity = newValue ? 1 : 0
      this.map.setPaintProperty('line-layer', 'line-opacity', opacity)
    },
    initializeMap () {
      this.map.addSource('myLine', {
        type: 'geojson',
        data: line,
      })
      this.map.addLayer({
        id: 'line-layer',
        type: 'line',
        source: 'myLine',
        paint: {
          'line-color': colorShades.primary,
          'line-width': 3,
        },
      })
      this.$watch('checkLine', this.onCheckLine)
    },
    onMapLoaded (event) {
      const bounds = new LngLatBounds()
      this.line.features[0].geometry.coordinates.forEach(coord => {
        bounds.extend(coord)
      })
      event.fitBounds(bounds, { padding: 100 })
      this.map = event
      this.map.on('load', this.initializeMap)
    },
  },
}
</script>
<template>
  <section class="map-view">
    <div
      class="left-panel elevation-4"
      :style="{'width': showLeftPanel ? '20%' : '0'}"
    >
      <div
        class="left-panel-toggle-btn elevation-4"
        :style="{'left': showLeftPanel ? 'calc(20%)' : '0px'}"
        @click="toggleShowLeftPanel"
      >
        <v-icon
          size="small"
          color="secondary"
        >
          {{ showLeftPanel ? 'fas fa-chevron-left' : 'fas fa-chevron-right' }}
        </v-icon>
      </div>
      <Transition name="slide-fade">
        <div v-show="showLeftPanelContent">
          <div class="left-panel-title">
            {{ $gettext('Legend') }}
          </div>
          <v-col class="left-panel-content">
            <v-checkbox
              v-model="checkPk"
              :label="$gettext('Markers')"
              color="primary"
              hide-details
            />
            <v-checkbox
              v-model="checkLine"
              :label="$gettext('Line')"
              color="primary"
              hide-details
            />
          </v-col>
        </div>
      </Transition>
    </div>
    <MapboxMap
      style="width: 100%; height: 100%; position:absolute;"
      :access-token="mapboxPublicKey"
      map-style="mapbox://styles/mapbox/light-v9"
      @mb-created="onMapLoaded"
    >
      <MapboxNavigationControl position="bottom-right" />
      <template v-if="checkPk">
        <MapboxMarker
          v-for="(point, index) in points"
          :key="`marker-${index}`"
          :lng-lat="point.geometry.coordinates"
          color="secondary"
          popup
        >
          <div class="pk-marker" />
          <template #popup>
            <div>
              {{ $gettext('Pk:') }} {{ point.properties.pk }}
            </div>
          </template>
        </MapboxMarker>
      </template>
    </MapboxMap>
  </section>
</template>
<style lang="scss" scoped>
.map-view {
  height: calc(100% - 50px);
  width: 100%;
  display: flex;
}
.left-panel {
  height: 100%;
  background-color: $white;
  transition: 0.3s;
  z-index: 20;
}
.left-panel-toggle-btn {
  position: absolute;
  left: 100%;
  width: 25px;
  z-index: 1;
  background-color: $white;
  display: flex;
  align-items: center;
  justify-content: center;
  height: 50px;
  transition: 0.3s;
  cursor: pointer;
}
.left-panel-title {
  height: 50px;
  line-height: 55px;
  padding-left: 20px;
  font-size: 1.1em;
  margin-bottom: 10px;
}
.left-panel-content {
  margin-left: 20px
}
.pk-marker {
  width: 15px;
  height: 15px;
  border-radius: 20px;
  background-color: $secondary;
}
</style>

// front/src/pages/MapPage.jsx
import { useEffect, useCallback, useRef, useState } from 'react'
import MapboxGL from 'mapbox-gl'
import 'mapbox-gl/dist/mapbox-gl.css'
import {
  Box,
  Button,
  Checkbox,
  FormControlLabel,
  Paper,
  Slide,
  Stack,
  Typography,
} from '@mui/material'
import { ChevronLeft, ChevronRight } from '@mui/icons-material'
import pkPoints from '@static/markers.json'
import line from '@static/line.json'
import colorShades from '@scss/sds-design-system/color-shades'
import { useI18n, T } from '@src/utils/i18n'
import { mapboxPublicKey } from '@src/config'
import './MapPage.scoped.scss'
import './MapPage.scss'

export default function MapPage() {
  const { t } = useI18n()
  const mapRef = useRef() // Mapbox instance
  const mapContainerRef = useRef() // DOM element for Mapbox
  const [showPanel, setShowPanel] = useState(false)
  const [panelContentVisible, setPanelContentVisible] = useState(false)
  const [showMarkers, setShowMarkers] = useState(true)
  const [showLine, setShowLine] = useState(true)
  const togglePanel = () => setShowPanel(shown => !shown)
  const fitLineBounds = useCallback(map => {
    const bounds = new MapboxGL.LngLatBounds()
    line.features[0].geometry.coordinates.forEach(coord => {
      bounds.extend(coord)
    })
    map.fitBounds(bounds, { padding: 100 })
  }, [])
  const drawMarkers = useCallback((map, showMarkers, showLine) => {
    map.setPaintProperty('line-layer', 'line-opacity', showLine ? 1 : 0)
    if (map._pkMarkers) { // Remove previous markers if any
      map._pkMarkers.forEach(m => m.remove())
    }
    if (showMarkers) {
      const markers = pkPoints.features.map(point => {
        const el = document.createElement('div')
        el.className = 'map-pk-marker'
        const marker = new MapboxGL.Marker({ element: el, color: colorShades.secondary })
          .setLngLat(point.geometry.coordinates)
          .setPopup(
            new MapboxGL.Popup({ offset: 25 }).setHTML(
              `<div>${t('Pk:')} ${point.properties.pk}</div>`,
            ),
          )
        marker.addTo(map)
        return marker
      })
      map._pkMarkers = markers
    }
  }, [t])
  useEffect(() => { /* Map Init */
    if (!mapRef.current) { // Create map only once
      MapboxGL.accessToken = mapboxPublicKey
      const map = new MapboxGL.Map({
        container: mapContainerRef.current,
        style: 'mapbox://styles/mapbox/light-v9',
        center: [0, 0],
        zoom: 2,
      })
      map.addControl(new MapboxGL.NavigationControl(), 'bottom-right')
      map.on('style.load', () => {
        map.setFog({}) // Set the default atmosphere style
      })
      map.on('load', () => {
        map.addSource('myLine', {
          type: 'geojson',
          data: line,
        })
        map.addLayer({
          id: 'line-layer',
          type: 'line',
          source: 'myLine',
          paint: {
            'line-color': colorShades.primary,
            'line-width': 3,
            'line-opacity': 1,
          },
        })
        drawMarkers(map, true, true)
        fitLineBounds(map)
      })
      mapRef.current = map
    }
  }, [drawMarkers, fitLineBounds])
  useEffect(() => { // react to checkbox changes
    const map = mapRef.current
    if (!map || !map.isStyleLoaded()) {
      return
    }
    drawMarkers(map, showMarkers, showLine)
  }, [drawMarkers, showMarkers, showLine])
  useEffect(() => {
    setPanelContentVisible(showPanel)
  }, [showPanel])
  return (
    <Box className="map-view">
      <Paper
        elevation="4"
        className="left-panel"
        sx={{ width: showPanel ? 'auto' : '25px' }}
      >
        <Button
          className="toggle-btn"
          sx={{
            left: showPanel ? 'auto' : 0,
            right: showPanel ? 0 : 'auto',
          }}
          onClick={togglePanel}
        >
          {showPanel ? <ChevronLeft /> : <ChevronRight />}
        </Button>
        <Slide direction="right" in={panelContentVisible} mountOnEnter unmountOnExit>
          <Box sx={{ p: 2, mt: 6 }}>
            <Typography variant="h6" gutterBottom>
              <T>Legend</T>
            </Typography>
            <Stack>
              <FormControlLabel
                label={t('Markers')}
                control={<Checkbox checked={showMarkers} onChange={(e) => setShowMarkers(e.target.checked)} />}
              />
              <FormControlLabel
                label={t('Line')}
                control={<Checkbox checked={showLine} onChange={(e) => setShowLine(e.target.checked)} />}
              />
            </Stack>
          </Box>
        </Slide>
      </Paper>
      <Box ref={mapContainerRef} className="map" />
    </Box>
  )
}
