// front/src/pages/Post.vue
<script>
import InformationPopup from '@comp/utils/InformationPopup.vue'
import Comment from '@comp/post/Comment.vue'
import CommentForm from '@comp/post/CommentForm.vue'
import { getPostQuery } from '@src/queries'
import {
  createCommentMutation,
  updateCommentMutation,
  deleteCommentMutation,
} from '@src/mutations'
import { backUrl } from '@src/config'
import { homeRoute } from '@src/router'
import { useIndexStore } from '@src/store'

export default {
  name: 'Post',
  components: {
    InformationPopup,
    Comment,
    CommentForm,
  },
  data () {
    return {
      post: {},
      showCommentAddDialog: false,
      currentComment: null,
      showCommentEditDialog: false,
      showCommentDeleteDialog: false,
    }
  },
  computed: {
    imageFullUrl () {
      if (this.post.imageUrl) {
        if (this.post.imageUrl[0] === '/') {
          return backUrl + this.post.imageUrl.substring(1)
        } else {
          return backUrl + this.post.imageUrl
        }
      } else {
        return null
      }
    },
    categories () {
      return this.post.categories || []
    },
    authorName () {
      return this.post.author ? this.post.author.fullName : ''
    },
    publicationDate () {
      return new Date(this.post.pubdate)
    },
    localeDate () {
      return this.publicationDate ? this.publicationDate.toLocaleDateString(this.$language.current) : ''
    },
    comments () {
      return this.post.comments
    },
    commentAddDialogButtons () {
      return [
        {
          class: 'cancel-btn',
          label: this.$gettext('Cancel'),
          icon: 'fas fa-times',
          event: 'cancelCommentAddDialog',
        },
        {
          class: 'save-btn',
          label: this.$gettext('Add'),
          icon: 'fas fa-save',
          type: 'submit',
        },
      ]
    },
    commentEditDialogButtons () {
      return [
        {
          class: 'cancel-btn',
          label: this.$gettext('Cancel'),
          icon: 'fas fa-times',
          event: 'cancelCommentEditDialog',
        },
        {
          class: 'save-btn',
          label: this.$gettext('Save'),
          icon: 'fas fa-save',
          type: 'submit',
        },
      ]
    },
    commentDeleteDialogButtons () {
      return [
        {
          class: 'cancel-btn',
          label: this.$gettext('Cancel'),
          icon: 'fas fa-times',
          event: 'cancelCommentDeleteDialog',
        },
        {
          class: 'delete-btn',
          label: this.$gettext('Delete'),
          icon: 'fas fa-trash',
          color: 'white',
          event: 'deleteComment',
        },
      ]
    },
  },
  async mounted () {
    const store = useIndexStore()
    store.changeRoute(this.$options.name)
    const postId = this.$route.params.id
    await this.setData(postId)
  },
  methods: {
    async setData (postId) {
      const { post } = await this.$graphqlQuery(
        getPostQuery,
        { id: postId },
      ).catch(console.error)
      this.post = post
    },
    goBack () {
      this.$router.push({ name: homeRoute.name })
    },
    onAddCommentButton () {
      this.showCommentAddDialog = true
    },
    cancelCommentAddDialog () {
      this.showCommentAddDialog = false
    },
    async addComment (isValid) {
      if (isValid) {
        const formData = this.$refs.commentAdd.formData
        await this.$graphqlMutate(
          createCommentMutation,
          {
            postId: this.post.id,
            text: formData.text,
            authorId: formData.author ? formData.author.id : null,
          },
        ).catch(console.error)
        // not subtile, refresh the whole post
        await this.setData(this.post.id)
        this.showCommentAddDialog = false
      }
    },
    onEditCommentButton (comment) {
      this.currentComment = comment
      this.showCommentEditDialog = true
    },
    cancelCommentEditDialog () {
      this.currentComment = null
      this.showCommentEditDialog = false
    },
    async editComment (isValid) {
      if (isValid) {
        const commentId = this.currentComment.id
        const formData = this.$refs.commentEdit.formData
        await this.$graphqlMutate(
          updateCommentMutation,
          {
            id: commentId,
            text: formData.text,
            authorId: formData.author.id,
          },
        ).catch(console.error)
        // not subtile, refresh the whole post
        await this.setData(this.post.id)
        this.cancelCommentEditDialog()
      }
    },
    onDeleteCommentButton (comment) {
      this.currentComment = comment
      this.showCommentDeleteDialog = true
    },
    cancelCommentDeleteDialog () {
      this.currentComment = null
      this.showCommentDeleteDialog = false
    },
    async deleteComment () {
      const commentId = this.currentComment.id
      await this.$graphqlMutate(
        deleteCommentMutation, { id: commentId },
      ).catch(console.error)
      // not subtile, refresh the whole post
      await this.setData(this.post.id)
      this.cancelCommentDeleteDialog()
    },
  },
}
</script>
<template>
  <section class="view">
    <div class="card post">
      <v-btn
        variant="tonal"
        color="secondary"
        prepend-icon="fas fa-arrow-left"
        class="back"
        @click="goBack"
      >
        {{ $gettext('Return') }}
      </v-btn>
      <div class="post-header">
        <div class="post-title">
          {{ post.title }}
        </div>
        <img
          v-if="imageFullUrl"
          class="post-image"
          :src="imageFullUrl"
        >
        <div class="post-author-date">
          {{ $gettext('Published by') }}
          <span class="author">{{ authorName }}</span>
          {{ $gettext('On') }}
          <span class="date">{{ localeDate }}</span>
        </div>
        <div
          v-if="categories.length"
          class="post-categories"
        >
          <v-btn
            v-for="category in categories"
            :key="category.id"
            :to="{ name: 'Category', params: { id: category.id } }"
            size="small"
            variant="tonal"
            color="secondary"
          >
            {{ category.name }}
          </v-btn>
        </div>
      </div>
      <div class="post-text">
        {{ post.text }}
      </div>
      <div class="post-comments">
        <div class="post-comments-header">
          {{ $gettext('Comments') }}
        </div>
        <div class="comments-container">
          <Comment
            v-for="comment in comments"
            :key="comment.id"
            :comment="comment"
            @edit-comment="onEditCommentButton(comment)"
            @delete-comment="onDeleteCommentButton(comment)"
          />
        </div>
        <v-btn
          color="primary"
          class="comment-add"
          prepend-icon="fas fa-plus"
          @click="onAddCommentButton"
        >
          {{ $gettext('Add a comment') }}
        </v-btn>
      </div>
      <InformationPopup
        v-model="showCommentAddDialog"
        :title="$gettext('Add a comment')"
        :buttons="commentAddDialogButtons"
        @cancel-comment-add-dialog="cancelCommentAddDialog"
        @submit-form="addComment"
      >
        <CommentForm
          v-if="showCommentAddDialog"
          ref="commentAdd"
        />
      </InformationPopup>
      <InformationPopup
        v-model="showCommentEditDialog"
        :title="$gettext('Edit a comment')"
        :buttons="commentEditDialogButtons"
        @cancel-comment-edit-dialog="cancelCommentEditDialog"
        @submit-form="editComment"
      >
        <CommentForm
          v-if="currentComment"
          ref="commentEdit"
          :comment="currentComment"
        />
      </InformationPopup>
      <InformationPopup
        v-model="showCommentDeleteDialog"
        :title="$gettext('Delete a comment')"
        :buttons="commentDeleteDialogButtons"
        @cancel-comment-delete-dialog="cancelCommentDeleteDialog"
        @delete-comment="deleteComment"
      >
        <div
          v-if="currentComment"
        >
          {{ `${$gettext('You are about to delete the comment')} « ${currentComment.date} ».
            ${$gettext('Do you really want to take that action?')}` }}
        </div>
      </InformationPopup>
    </div>
  </section>
</template>
<style lang="scss" scoped>
div.post {
  height: inherit;
  overflow-y: auto;
  display: flex;
  flex-direction: column;
  gap: 1.5rem;
  flex-grow: 1;
  flex-shrink: 1;
}
button.back {
  align-self: flex-start;
}
div.post-title {
  font-weight: bold;
  font-size: 2em;
}
.post-image {
  display: block;
  max-width: 400px;
  max-height: 200px;
}
.post-author-date {
  font-weight: 300;
  font-size: 1.2rem;
}
div.post-categories {
  display: flex;
  gap: 1ch;
}
.author {
  font-weight: 700;
  color: navy;
}
.date {
  font-style: italic;
}
div.post-comments {
  border-top: 1px solid black;
  width: 100%;
}
.post-comments-header {
  font-size: 1.2rem;
}
.comments-container {
  display: flex;
  flex-direction: column;
  gap: 1ch;
  margin-bottom: 2rem;
}
</style>

// front/src/pages/Post.jsx
import { useCallback, useEffect, useMemo, useState } from 'react'
import { NavLink, useNavigate, useParams } from 'react-router-dom'
import {
  Add,
  ArrowBack,
  Delete,
  Edit,
} from '@mui/icons-material'
import {
  Box,
  Button,
  Card,
  Stack,
  Typography,
} from '@mui/material'
import Comment from '@comp/post/Comment'
import CommentForm from '@comp/post/CommentForm'
import InformationPopup from '@comp/utils/InformationPopup'
import { backUrl } from '@src/config'
import useGraphql from '@src/graphql'
import { createCommentMutation, deleteCommentMutation, updateCommentMutation } from '@src/graphql/mutations'
import { getPostQuery } from '@src/graphql/queries'
import { T, useI18n } from '@src/i18n'
import useRoutes from '@src/routes'

export default function Post() {
  const { id: postId } = useParams()
  const navigate = useNavigate()
  const { HomeRoute, CategoryRoute } = useRoutes()
  const { graphqlQuery, graphqlMutate } = useGraphql()
  const { t, locale } = useI18n()

  const [post, setPost] = useState({})
  const fetchPost = useCallback(async (setPost) => {
    try {
      const { post } = await graphqlQuery(getPostQuery, { id: postId })
      setPost(post)
    } catch (err) {
      console.error(err)
    }
  }, [graphqlQuery, postId])
  const pushAddComment = useCallback(async (comment) => {
    try {
      await graphqlMutate(
        createCommentMutation,
        {
          postId,
          text: comment.text,
          authorId: comment.author.id,
        },
      )
    } catch (err) {
      console.error(err)
    }
  }, [graphqlMutate, postId])
  const pushEditComment = useCallback(async (comment) => {
    try {
      await graphqlMutate(
        updateCommentMutation,
        {
          id: comment.id,
          text: comment.text,
          authorId: comment.author.id,
        },
      )
    } catch (err) {
      console.error(err)
    }
  }, [graphqlMutate])
  const pushDeleteComment = useCallback(async (comment) => {
    try {
      await graphqlMutate(
        deleteCommentMutation,
        { id: comment.id },
      )
    } catch (err) {
      console.error(err)
    }
  }, [graphqlMutate])
  useEffect(() => {
    fetchPost(setPost)
  }, [fetchPost, postId])
  const imageFullUrl = useMemo(() => {
    if (post.imageUrl) {
      if (post.imageUrl[0] === '/') {
        return backUrl + post.imageUrl.substring(1)
      } else {
        return backUrl + post.imageUrl
      }
    } else {
      return null
    }
  }, [post])
  const authorName = post.author?.fullName || ''
  const publicationDate = new Date(post.pubdate)
  const localeDate = publicationDate ? publicationDate.toLocaleDateString(locale) : ''
  const categories = post.categories || []

  const [currentComment, setCurrentComment] = useState(null)
  const [showAdd, setShowAdd] = useState(false)
  const [showEdit, setShowEdit] = useState(false)
  const [showDelete, setShowDelete] = useState(false)

  function goBack() {
    navigate({ pathname: HomeRoute.path })
  }

  function openAdd() {
    setShowAdd(true)
  }
  async function handleAdd() {
    await pushAddComment(currentComment)
    await fetchPost(setPost)
    cancelAdd()
  }
  function cancelAdd() {
    setShowAdd(false)
  }

  function openEdit(comment) {
    setCurrentComment(comment)
    setShowEdit(true)
  }
  async function handleEdit() {
    await pushEditComment(currentComment)
    await fetchPost(setPost)
    cancelEdit()
  }
  function cancelEdit() {
    setShowEdit(false)
    setCurrentComment(null)
  }

  function openDelete(comment) {
    setCurrentComment(comment)
    setShowDelete(true)
  }
  async function handleDelete() {
    await pushDeleteComment(currentComment)
    await fetchPost(setPost)
    cancelDelete()
  }
  function cancelDelete() {
    setShowDelete(false)
    setCurrentComment(null)
  }

  return (
    <Box sx={{ p: 2 }}>
      <Card sx={{ display: 'flex', flexDirection: 'column', gap: 3, p: 3 }}>
        <Button
          variant="contained"
          color="secondary"
          startIcon={<ArrowBack />}
          onClick={goBack}
          sx={{ alignSelf: 'flex-start' }}
        >
          <T>Return</T>
        </Button>
        {/* Header */}
        <Box>
          <Typography variant="h4">
            {post.title}
          </Typography>
          {imageFullUrl && (
            <Box component="img" src={imageFullUrl} alt="Post image" sx={{ maxWidth: 400, maxHeight: 200 }} />
          )}
          <Typography variant="subtitle1">
            Published by
            {' '}
            <span>{authorName}</span>
            {' '}
            on
            {' '}
            <span>{localeDate}</span>
          </Typography>
          {categories.length > 0 && (
            <Stack direction="row" spacing={1}>
              {categories.map(cat => (
                <Button
                  key={cat.id}
                  component={NavLink}
                  to={CategoryRoute.pathParams({ id: cat.id })}
                  size="small"
                  variant="contained"
                  color="secondary"
                >
                  {cat.name}
                </Button>
              ))}
            </Stack>
          )}
        </Box>
        {/* Body */}
        <Typography>{post.text}</Typography>
        {/* Comments */}
        <Box sx={{ borderTop: '1px solid black', mt: 4, pt: 2 }}>
          <Typography variant="h6">
            <T>Comments</T>
          </Typography>
          <Stack spacing={1} sx={{ mb: 2 }}>
            {post.comments?.map(comment => (
              <Comment
                key={comment.id}
                comment={comment}
                onEditComment={() => { openEdit(comment) }}
                onDeleteComment={() => { openDelete(comment) }}
              />
            ))}
          </Stack>
          <Button
            variant="contained"
            color="primary"
            startIcon={<Add />}
            onClick={openAdd}
          >
            <T>Add a comment</T>
          </Button>
        </Box>
        {/* Add Dialog */}
        <InformationPopup
          open={showAdd}
          title={t('Add a comment')}
          buttons={[
            { type: 'cancel', label: t('Cancel') },
            { type: 'submit', label: t('Add'), icon: (<Add />) },
          ]}
          onCancel={cancelAdd}
          onSubmit={handleAdd}
        >
          <CommentForm onChange={comment => setCurrentComment(comment)} />
        </InformationPopup>
        {/* Edit Dialog */}
        <InformationPopup
          open={showEdit}
          title={t('Edit a comment')}
          buttons={[
            { type: 'cancel', label: t('Cancel') },
            { type: 'submit', label: t('Edit'), icon: (<Edit />) },
          ]}
          onCancel={cancelEdit}
          onSubmit={handleEdit}
        >
          {currentComment && (
            <CommentForm
              comment={currentComment}
              onChange={comment => setCurrentComment({ ...currentComment, ...comment })}
            />
          )}
        </InformationPopup>
        {/* Delete Dialog */}
        <InformationPopup
          open={showDelete}
          title={t('Delete a comment')}
          buttons={[
            { type: 'cancel', label: t('Cancel') },
            { type: 'submit', label: t('Delete'), icon: (<Delete />), color: 'error' },
          ]}
          onCancel={cancelDelete}
          onSubmit={handleDelete}
        >
          {currentComment && (
            <Box>
              <T
                one="You are about to delete the comment « {{ comment }} ». Do you really want to take that action?"
                comment={currentComment.date}
              />
            </Box>
          )}
        </InformationPopup>
      </Card>
    </Box>
  )
}
